name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  PHPUnit:
    name: PHPUnit (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - "8.4"
          - "8.3"
          - "8.2"
          - "8.1"
          - "8.0"
          - "7.4"
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: apcu
          tools: phpunit:9, composer:v2
          coverage: none
          ini-values: apc.enabled=1, apc.enable_cli=1, apc.shm_segments=1, apc.shm_size=256M
      - run: composer install
      - run: vendor/bin/phpunit
